package io.github.dftrakesh.model.product;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;

import java.util.List;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class Product {
    private Integer id;
    private String sku;
    private String thumbnailUrl;
    private Boolean unlimited;
    private Boolean inStock;
    private String name;
    private Integer price;
    private Integer priceInProductList;
    private Integer defaultDisplayedPrice;
    private String defaultDisplayedPriceFormatted;
    private Integer costPrice;
    private Tax tax;
    private Boolean isShippingRequired;
    private Boolean hasFreeShipping;
    private Integer weight;
    private String url;
    private String autogeneratedSlug;
    private String customSlug;
    private String created;
    private String updated;
    private Integer createTimestamp;
    private Integer updateTimestamp;
    private Integer productClassId;
    private Boolean enabled;
    private List<Option> options;
    private Integer warningLimit;
    private Boolean fixedShippingRateOnly;
    private Integer fixedShippingRate;
    private Shipping shipping;
    private Integer defaultCombinationId;
    private String imageUrl;
    private String smallThumbnailUrl;
    private String hdThumbnailUrl;
    private String originalImageUrl;
    private OriginalImage originalImage;
    private String description;
    private List<GalleryImage> galleryImages;
    private Media media;
    private List<Number> categoryIds;
    private Integer defaultCategoryId;
    private String seoTitle;
    private String seoDescription;
    private RelatedProducts relatedProducts;
    private Boolean showDeliveryTimeInStorefront;
    private Integer volume;
    private Integer showOnFrontpage;
    private Boolean isSampleProduct;
    private String googleItemCondition;
    private Boolean isGiftCard;
    private Boolean discountsAllowed;
    private Boolean nameYourPriceEnabled;
    private String productCondition;
    private String outOfStockVisibilityBehaviour;
}