package model.product;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import java.util.List;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class Product{
    private int id;
    private String sku;
    private String thumbnailUrl;
    private boolean unlimited;
    private boolean inStock;
    private String name;
    private NameTranslated nameTranslated;
    private int price;
    private int priceInProductList;
    private int defaultDisplayedPrice;
    private String defaultDisplayedPriceFormatted;
    private int costPrice;
    private Tax tax;
    private boolean isShippingRequired;
    private boolean hasFreeShipping;
    private int weight;
    private String url;
    private String autogeneratedSlug;
    private String customSlug;
    private String created;
    private String updated;
    private int createTimestamp;
    private int updateTimestamp;
    private int productClassId;
    private boolean enabled;
    private List<Option> options;
    private int warningLimit;
    private boolean fixedShippingRateOnly;
    private int fixedShippingRate;
    private Shipping shipping;
    private int defaultCombinationId;
    private String imageUrl;
    private String smallThumbnailUrl;
    private String hdThumbnailUrl;
    private String originalImageUrl;
    private OriginalImage originalImage;
    private BorderInfo borderInfo;
    private String description;
    private DescriptionTranslated descriptionTranslated;
    private List<GalleryImage> galleryImages;
    private Media media;
    private List<Object> categoryIds;
    private List<Object> categories;
    private int defaultCategoryId;
    private String seoTitle;
    private SeoTitleTranslated seoTitleTranslated;
    private String seoDescription;
    private SeoDescriptionTranslated seoDescriptionTranslated;
    private List<Object> attributes;
    private List<Object> files;
    private RelatedProducts relatedProducts;
    private List<Object> combinations;
    private boolean showDeliveryTimeInStorefront;
    private int volume;
    private int showOnFrontpage;
    private boolean isSampleProduct;
    private String googleItemCondition;
    private boolean isGiftCard;
    private boolean discountsAllowed;
    private boolean nameYourPriceEnabled;
    private String productCondition;
    private String outOfStockVisibilityBehaviour;
}

